import Link from "next/link"
import { ArrowRight, Archive, BookOpen, Check, Clock3, FileText, Quote, Sparkles, Upload } from "lucide-react"

const highlights = [
  { title: "Physics Official Board Paper", subject: "Physics", year: "2024", pages: "12 pages", tone: "amber" },
  { title: "English Literature Prelim", subject: "English Literature", year: "2022", pages: "8 pages", tone: "blue" },
  { title: "Commercial Studies Notes", subject: "Commercial Studies", year: "2025", pages: "24 pages", tone: "lavender" },
]

export default function Home() {
  return <main className="site-shell">
    <header className="site-header"><Link href="/" className="brand"><span className="brand-mark">P</span><span><strong>Papyrus</strong><small>Built for the prep. Driven by students.</small></span></Link><nav className="nav-links"><Link href="/archive">Archive</Link><Link href="#about">How it works</Link><Link href="/upload">Community upload</Link><Link href="/settings">Settings</Link></nav><div className="header-actions"><Link href="/upload" className="button button-soft"><Upload size={16}/> Upload resource</Link><Link href="/archive" className="button button-dark">Browse archive <ArrowRight size={16}/></Link></div><Link href="/archive" className="mobile-archive" aria-label="Open archive"><Archive size={19}/></Link></header>
    <section className="hero landing-hero"><div className="eyebrow"><span className="status-dot"/> The student paper archive <i/> Open by design</div><h1>Study from the<br/><em>source material.</em></h1><p>A calm, community-built home for authentic ICSE &amp; ISC papers, school prelims, and notes worth passing forward.</p><div className="hero-actions"><Link href="/archive" className="button button-dark">Explore the archive <ArrowRight size={16}/></Link><Link href="#about" className="text-link">See how Papyrus works <ArrowRight size={16}/></Link></div><div className="hero-stamp"><span>EST. 2026</span><strong>ARCHIVE<br/>NO. 001</strong><span>ICSE · ISC</span></div></section>
    <section className="archive-intro" id="about"><div className="section-heading"><div><p className="kicker">A BETTER KIND OF STUDY TOOL</p><h2>Less hunting.<br/><em>More understanding.</em></h2></div><p className="intro-copy">Papyrus brings the papers students actually need into one searchable, readable archive. Every upload is catalogued, previewed, and shared without a paywall.</p></div><div className="principles"><article><span className="principle-icon"><Archive size={18}/></span><p className="card-label">01 / FIND</p><h3>Everything in one place</h3><p>Search by subject, board, year, or paper type instead of ten open tabs.</p></article><article><span className="principle-icon"><BookOpen size={18}/></span><p className="card-label">02 / READ</p><h3>Preview before you download</h3><p>See the paper&apos;s shape and sections first, with a distraction-free reader.</p></article><article><span className="principle-icon"><Sparkles size={18}/></span><p className="card-label">03 / SHARE</p><h3>Keep the archive growing</h3><p>Pass forward the papers, notes, and knowledge that helped you prepare.</p></article></div></section>
    <section className="featured-section"><div className="section-heading"><div><p className="kicker">FROM THE STACKS</p><h2>Recently catalogued.</h2></div><Link className="text-link" href="/archive">View all papers <ArrowRight size={15}/></Link></div><div className="featured-grid">{highlights.map((item, index) => <Link href={`/paper/${["physics-2024", "english-2022", "commercial-2025"][index]}`} className="featured-card" key={item.title}><div className={`paper-thumb ${item.tone}`}><div className="paper-lines"/><span className="paper-label">{item.subject.slice(0, 2).toUpperCase()}</span><span className="paper-year">{item.year}</span></div><div><div className="card-meta"><span>VERIFIED SCAN</span><span>{item.pages}</span></div><h3>{item.title}</h3><p><Clock3 size={13}/> 18 min read <span>·</span> Added {index + 2} days ago</p></div></Link>)}</div></section>
    <section className="quote-section"><Quote size={22}/><blockquote>&quot;The best study material is the material someone cared enough to save.&quot;</blockquote><p>— A note from the archive</p></section>
    <section className="cta-section"><div><p className="kicker">YOUR NOTES MATTER</p><h2>Have a paper we&apos;re missing?</h2><p>Help thousands of students study smarter by adding a resource to the community archive.</p></div><Link href="/upload" className="button button-dark">Share a resource <ArrowRight size={16}/></Link></section><footer className="site-footer"><span>© 2026 Papyrus Archive</span><span>Made for the late-night learners.</span><Link href="/settings"><FileText size={13}/> Preferences</Link></footer>
  </main>
}
