import './style.css'

type Resource={id:string;title:string;subject:string;year:string;board:string;type:string;read:string;tone:string;summary:string}
type Group={id:string;name:string}
type Pin={id:string;groupId:string;pinnedAt:number}
const resources:Resource[]=[
{id:'physics-2024',title:'Physics — Paper 2',subject:'Physics',year:'2024',board:'AQA',type:'Exam paper',read:'12 min',tone:'amber',summary:'A clean set of mechanics and fields questions with examiner-style prompts.'},
{id:'maths-2023',title:'Mathematics — Pure',subject:'Mathematics',year:'2023',board:'OCR',type:'Study notes',read:'8 min',tone:'blue',summary:'A concise revision sheet for calculus, proof, and algebraic reasoning.'},
{id:'chem-2024',title:'Chemistry — Organic',subject:'Chemistry',year:'2024',board:'Edexcel',type:'Exam paper',read:'15 min',tone:'sage',summary:'Organic synthesis pathways annotated by a student study group.'},
{id:'lit-2022',title:'The Great Gatsby — Context',subject:'English Literature',year:'2022',board:'AQA',type:'Essay plan',read:'6 min',tone:'rose',summary:'Context cards and a model argument for the modernist classic.'},
{id:'physics-2021',title:'Waves & Optics',subject:'Physics',year:'2021',board:'OCR',type:'Revision guide',read:'10 min',tone:'lavender',summary:'Diagrams, definitions, and the equations most worth remembering.'},
{id:'maths-2024',title:'Statistics — Practice Set',subject:'Mathematics',year:'2024',board:'AQA',type:'Practice set',read:'18 min',tone:'peach',summary:'Mixed probability and statistics problems with space to work.'},
]
const defaultGroups:Group[]=[{id:'study',name:'Study list'},{id:'exam',name:'Exam week'},{id:'review',name:'Review later'}]
const app=document.querySelector<HTMLDivElement>('#app')!
const getGroups=():Group[]=>JSON.parse(localStorage.getItem('papyrus-groups')||'null')||defaultGroups
const getPins=():Pin[]=>JSON.parse(localStorage.getItem('papyrus-pins')||'[]')
const save=(groups:Group[],pins:Pin[])=>{localStorage.setItem('papyrus-groups',JSON.stringify(groups));localStorage.setItem('papyrus-pins',JSON.stringify(pins))}
const icon=(name:string)=>({search:'⌕',pin:'⌖',arrow:'←',moon:'◐',sun:'☼',close:'×',book:'▤',plus:'+',settings:'⚙',home:'⌂',archive:'▤',upload:'↥'}[name]||'•')
const nav=()=>`<header class="site-header"><a class="brand" href="#/"><span class="brand-mark">P</span><span><strong>Papyrus</strong><small>Built for the prep. Driven by students.</small></span></a><nav><a href="#/">${icon('home')}<span>Home</span></a><a href="#/archive">${icon('archive')}<span>Archive</span></a><a href="#/pins">${icon('pin')}<span>Pins</span> <b class="pin-count">${getPins().length||''}</b></a><a href="#/upload">${icon('upload')}<span>Community upload</span></a><a href="#/settings">${icon('settings')}<span>Settings</span></a></nav><button class="theme-button" data-theme-toggle aria-label="Toggle dark mode">${document.documentElement.classList.contains('dark')?icon('sun'):icon('moon')}</button></header>`
const subjectClass=(subject:string)=>subject.toLowerCase().replace(/\s+/g,'-')
const paperThumb=(r:Resource)=>`<div class="paper-thumb ${r.tone} subject-${subjectClass(r.subject)}"><span class="subject-badge">${r.subject}</span><span class="paper-year">${r.year}</span><span class="paper-lines"></span><strong>${r.subject}</strong><small>${r.type}</small></div>`
function pinControl(id:string){const pinned=getPins().find(p=>p.id===id);return `<div class="pin-control"><button class="pin-main ${pinned?'pinned':''}" data-pin="${id}">${icon('pin')} ${pinned?'Pinned':'Pin paper'}</button><button class="pin-menu-trigger" data-menu="${id}" aria-label="Choose pin group">⌄</button><div class="pin-menu" data-menu-panel="${id}"><small>PIN TO GROUP</small>${getGroups().map(g=>`<button data-group="${g.id}" data-paper="${id}">${g.name}${pinned?.groupId===g.id?' ✓':''}</button>`).join('')}<button class="new-group" data-new-group="${id}">${icon('plus')} New pin group</button></div></div>`}
const card=(r:Resource)=>`<article class="resource-card" style="--card-index:${resources.findIndex(x=>x.id===r.id)}">${paperThumb(r)}<div class="resource-info"><div class="resource-meta"><span>${r.board}</span><span>${r.read} read</span></div><h3>${r.title}</h3><p>${r.summary}</p><div class="resource-footer"><a class="text-link" href="#/paper/${r.id}">View paper →</a>${pinControl(r.id)}</div></div></article>`
function layout(content:string){app.innerHTML=`${nav()}${content}<footer><span>© 2026 Papyrus Archive</span><span>Made for curious students, everywhere.</span></footer>`;bindGlobal()}
function home(){layout(`<main><section class="hero"><p class="eyebrow">THE STUDENT ARCHIVE / EST. 2026</p><h1>Good work<br/><em>deserves</em> good<br/>company.</h1><p class="hero-copy">Papyrus is a living archive of papers, notes, and study guides — shared by students, for students.</p><div class="hero-actions"><a class="button button-dark" href="#/archive">Explore the archive →</a><a class="button button-ghost" href="#/upload">Share a resource</a></div><div class="hero-stamp"><span>CATALOGUE NO. 001</span><strong>AUTHENTIC PAPERS<br/>CURATED NOTES</strong><span>OPEN ACCESS</span></div></section><section class="intro"><div><p class="kicker">A BETTER WAY TO PREPARE</p><h2>Less searching.<br/><em>More finding.</em></h2></div><p>Skip the noisy group chats and scattered folders. Papyrus brings the good stuff into one calm, searchable place.</p></section><section class="principles"><article><b>${icon('book')}</b><h3>Collected with care</h3><p>Every resource is catalogued with its subject, year, and paper type.</p></article><article><b>${icon('pin')}</b><h3>Keep your own shelf</h3><p>Pin papers into focused groups for your next study session.</p></article><article><b>${icon('search')}</b><h3>Find your thread</h3><p>Search by topic, board, year, or the exact phrase you remember.</p></article></section><section class="quote"><blockquote>“The archive is not a graveyard. It is a map of where we have been — and where we might go next.”</blockquote><small>— CATALOGUE NOTE 01</small></section></main>`)}
function archive(){let query='',filter='All resources',sort='Newest first';const render=()=>{const list=resources.filter(r=>`${r.title} ${r.subject} ${r.year} ${r.type} ${r.board}`.toLowerCase().includes(query.toLowerCase())&&(filter==='All resources'||r.subject===filter)).sort((a,b)=>sort==='Oldest first'?+a.year-+b.year:+b.year-+a.year);layout(`<main><section class="page-heading"><p class="kicker">THE COMMUNITY ARCHIVE / 2026</p><h1>Find exactly what<br/><em>you need.</em></h1><p>Search the stack of authentic papers, prelims, and notes. Catalogued by students, for students.</p></section><section class="explorer"><div class="search-panel"><div class="search-box"><span>${icon('search')}</span><input id="search" autofocus placeholder="Search title, subject, year, or paper type..." value="${query}"/><kbd>⌘ K</kbd>${query?`<button data-clear>${icon('close')}</button>`:''}</div><div class="search-help"><span>Try “2024 physics”</span><span>${list.length} papers found</span></div></div><label class="sort">Sort <select id="sort"><option ${sort==='Newest first'?'selected':''}>Newest first</option><option ${sort==='Oldest first'?'selected':''}>Oldest first</option></select></label></div><div class="filters"><button class="${filter==='All resources'?'active':''}" data-filter="All resources">All resources</button>${['Physics','Mathematics','Chemistry','English Literature'].map(s=>`<button class="${filter===s?'active':''}" data-filter="${s}">${s}</button>`).join('')}</div><div class="catalog-line"><span>Showing ${list.length} of ${resources.length} resources</span><span>Catalogued by the Papyrus community</span></div>${list.length?`<div class="resource-grid">${list.map(card).join('')}</div>`:`<div class="empty"><h2>Nothing in this drawer.</h2><p>Try a broader search or clear the filters.</p><button class="button button-soft" data-clear>Clear search</button></div>`}</section></main>`);document.querySelector<HTMLInputElement>('#search')?.addEventListener('input',e=>{query=(e.target as HTMLInputElement).value;render()});document.querySelector<HTMLSelectElement>('#sort')?.addEventListener('change',e=>{sort=(e.target as HTMLSelectElement).value;render()});document.querySelectorAll<HTMLElement>('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter||'All resources';render()});document.querySelectorAll<HTMLElement>('[data-clear]').forEach(b=>b.onclick=()=>{query='';filter='All resources';render()})};render()}
function pins(){const groups=getGroups();let active=groups[0]?.id||'study';const render=()=>{const selected=groups.find(g=>g.id===active)||groups[0];const list=getPins().filter(p=>p.groupId===selected?.id).map(p=>resources.find(r=>r.id===p.id)).filter(Boolean) as Resource[];layout(`<main class="pins-page"><p class="kicker">YOUR PERSONAL SHELF</p><h1>Keep what<br/><em>matters.</em></h1><p class="lead">Pin useful papers into groups so the right material is always close when you need it.</p><div class="groups">${groups.map(g=>`<button class="group-tab ${g.id===active?'active':''}" data-active-group="${g.id}"><strong>${g.name}</strong><span>${getPins().filter(p=>p.groupId===g.id).length} papers</span></button>`).join('')}</div><div class="catalog-line"><span>${selected?.name||'Your pins'}</span><span>${list.length} pinned</span></div>${list.length?`<div class="resource-grid">${list.map(card).join('')}</div>`:`<div class="empty"><div class="empty-icon">${icon('pin')}</div><h2>Your shelf is waiting.</h2><p>Pin a paper from the archive and it will appear here.</p><a class="button button-dark" href="#/archive">Browse archive →</a></div>`}</main>`);document.querySelectorAll<HTMLElement>('[data-active-group]').forEach(b=>b.onclick=()=>{active=b.dataset.activeGroup||active;render()})};render()}
function settings(){layout(`<main class="settings"><p class="kicker">PAPYRUS PREFERENCES</p><h1>Make it<br/><em>yours.</em></h1><p class="lead">Small controls for a calmer study space.</p><section class="settings-card"><h2>Appearance</h2><div class="setting"><div><strong>Colour mode</strong><p>Choose the atmosphere for your archive.</p></div><div class="mode-buttons"><button data-mode="light">${icon('sun')} Light</button><button data-mode="dark">${icon('moon')} Dark</button></div></div></section><section class="settings-card"><h2>About Papyrus</h2><div class="setting"><strong>Version</strong><span>0.3 / Archive edition</span></div><div class="setting"><strong>Storage</strong><span>Local to this browser</span></div></section></main>`);document.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.onclick=()=>{setTheme(b.dataset.mode==='dark'?'dark':'light');settings()})}
function detail(id:string){const r=resources.find(x=>x.id===id)||resources[0];layout(`<main class="detail"><a class="breadcrumb" href="#/archive">← Back to archive</a><div class="detail-layout"><article><div class="document"><div class="doc-page"><span>CATALOGUE / ${r.year}</span><h2>${r.title}</h2><p>${r.summary}</p><hr/><h4>CONTENTS</h4><p>01. Overview<br/>02. Core concepts<br/>03. Practice questions<br/>04. Further reading</p><hr/><p class="fake-lines">Definitions, examples, and carefully arranged prompts for focused study.</p></div></div></article><aside class="sidebar"><section><small>ABOUT THIS PAPER</small><div class="metadata"><span>Subject<strong>${r.subject}</strong></span><span>Board<strong>${r.board}</strong></span><span>Format<strong>${r.type}</strong></span><span>Reading time<strong>${r.read}</strong></span></div><a class="download" href="#">Download PDF</a>${pinControl(r.id)}</section><section><small>RELATED PAPERS</small>${resources.filter(x=>x.id!==r.id&&x.subject===r.subject).slice(0,2).map(x=>`<a class="related" href="#/paper/${x.id}">${x.title}<span>${x.year}</span></a>`).join('')}</section></aside></div></main>`)}
function upload(){layout(`<main class="upload"><p class="kicker">COMMUNITY CONTRIBUTION</p><h1>Put something<br/><em>good back.</em></h1><p class="lead">Share a paper, guide, or note that made a difference to your prep.</p><form class="settings-card" id="upload-form"><label>Paper title<input required placeholder="e.g. Physics — Paper 2"/></label><label>Subject<select><option>Physics</option><option>Mathematics</option><option>Chemistry</option><option>English Literature</option></select></label><label>Choose a file<input type="file" required/></label><button class="button button-dark">Submit resource →</button></form></main>`);document.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();(e.currentTarget as HTMLElement).innerHTML='<div class="success"><div>✓</div><h2>Thank you for contributing.</h2><p>Your resource has joined the moderation queue.</p><a class="button button-soft" href="#/archive">Return to archive</a></div>'})}
function showNewGroup(paperId?:string){const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="modal-close" data-close>${icon('close')}</button><p class="kicker">NEW COLLECTION</p><h2 id="modal-title">Name your pin group.</h2><p>Give your shelf a name that makes sense for the way you study.</p><input id="group-name" autofocus placeholder="e.g. Final review" maxlength="32"/><div class="modal-actions"><button class="button button-ghost" data-close>Cancel</button><button class="button button-dark" data-create>Create group</button></div></div>`;document.body.append(modal);const close=()=>modal.remove();modal.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',close));const create=()=>{const input=modal.querySelector<HTMLInputElement>('#group-name')!;const name=input.value.trim();if(!name){input.classList.add('invalid');input.focus();return}const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+Date.now();const groups=[...getGroups(),{id,name}];const pins=getPins();if(paperId)pins.push({id:paperId,groupId:id,pinnedAt:Date.now()});save(groups,pins);close();render()};modal.querySelector('[data-create]')?.addEventListener('click',create);modal.querySelector('input')?.addEventListener('keydown',e=>{if(e.key==='Enter')create()})}
function bindGlobal(){document.querySelector('[data-theme-toggle]')?.addEventListener('click',()=>{setTheme(document.documentElement.classList.contains('dark')?'light':'dark')});document.querySelectorAll<HTMLElement>('[data-pin]').forEach(b=>b.onclick=()=>{const id=b.dataset.pin!;const pins=getPins();const found=pins.find(p=>p.id===id);save(getGroups(),found?pins.filter(p=>p.id!==id):[...pins,{id,groupId:getGroups()[0].id,pinnedAt:Date.now()}]);render()});document.querySelectorAll<HTMLElement>('[data-menu]').forEach(b=>b.onclick=e=>{e.stopPropagation();document.querySelector(`[data-menu-panel="${b.dataset.menu}"]`)?.classList.toggle('open')});document.querySelectorAll<HTMLElement>('[data-group]').forEach(b=>b.onclick=()=>{const id=b.dataset.paper!,groupId=b.dataset.group!;save(getGroups(),[...getPins().filter(p=>p.id!==id),{id,groupId,pinnedAt:Date.now()}]);render()});document.querySelectorAll<HTMLElement>('[data-new-group]').forEach(b=>b.onclick=()=>showNewGroup(b.dataset.newGroup));document.addEventListener('click',()=>document.querySelectorAll('.pin-menu.open').forEach(m=>m.classList.remove('open')),{once:true})}
function setTheme(theme:string){document.documentElement.classList.toggle('dark',theme==='dark');localStorage.setItem('papyrus-theme',theme);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#171a1d':'#fdfbf7');render()}
function render(){const path=location.hash.slice(1)||'/';if(path.startsWith('/paper/'))detail(path.split('/')[2]);else if(path==='/archive')archive();else if(path==='/pins')pins();else if(path==='/settings')settings();else if(path==='/upload')upload();else home()}
if(localStorage.getItem('papyrus-theme')==='dark')document.documentElement.classList.add('dark');window.addEventListener('hashchange',render);render()
